#cgates: 11/1/2017

language: python
python:
    - "2.7"
    - "3.4"
env:
    global:
        - COVERALLS_PARALLEL=true
    matrix:
        - PYSAM_VERSION=0.8.3
        - PYSAM_VERSION=0.8.4
        - PYSAM_VERSION=0.9.0
        - PYSAM_VERSION=0.10.0
        - PYSAM_VERSION=0.11.0
        - PYSAM_VERSION=0.12.0
install:
    - pip install `grep cython requirements.txt`
    - pip install -q pysam==$PYSAM_VERSION
    - pip install -q -r requirements.txt

before_script:
    - pip install coverage
    - pip install coveralls

script:
    - nosetests -s --with-coverage --verbose --cover-package=katana
    - nosetests -s examples

after_success:
    - coveralls

notifications:
    webhooks: https://coveralls.io/webhook?repo_token=48uc5NnD0P170im3VqZZCvGWNjXt6CQqC
    email:
        - cgates@umich.edu